name: FransetCore
version: 1.3
main: org.kelsi.fransetcore
api-version: 1.16
authors: [ Kelsi ]
commands:
  broadcast:
    aliases: [bc, bcast]
  me:
    usage: "/me <действие>\nНапример: /me открыл дверь"
  do:
    usage: "/do <действие>\nНапример: /do яблоко в руке"
  try:
    usage: "/try <действие>\nНапример: /try мягко приземлился"
  roll:
    usage: "/roll <сообщение>"
  setevent:
    usage: "/setevent"
    aliases: [se]
  removeevent:
    usage: "/removeevent"
    aliases: [re, de, deleteevent]
  event:
    usage: "/event"
  mobvote:
    usage: "/mobvote Тыква\n
    /mobvote Призрак\n
    /mobvote Босс-Призрак"
  spawn:
    usage: "/spawn - чтобы телепортироваться на спавн\n /spawn set - чтобы установить точку спавна"
    aliases: [hub, спавн, хаб]